RestClients:
  #The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
  DocuSign (DocuSign REST API):
    UUID: 3d3d7114-4397-48c9-8378-931fc35885c3
    Url: https://www.docusign.net/restapi
    Icon: res:/webContent/icons/docusign.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.connector.docusign.auth.OAuth2Feature
    Properties:
      AUTH.integrationKey: ${ivy.var.docusign-connector.integrationKey}
      AUTH.secretKey: ${ivy.var.docusign-connector.secretKey}
      AUTH.accountId: ${ivy.var.docusign-connector.accountId}
      AUTH.jwtUse: ${ivy.var.docusign-connector.jwt.use}
      AUTH.jwtUserId: ${ivy.var.docusign-connector.jwt.userId}
      AUTH.jwtKeyFile: ${ivy.var.docusign-connector.jwt.keyFile}
      AUTH.scope: ${ivy.var.docusign-connector.scope}
      AUTH.baseUri: ${ivy.var.docusign-connector.baseUri}
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
      PATH.accountId: placeholder
    OpenAPI:
      SpecUrl: https://github.com/docusign/eSign-OpenAPI-Specification/raw/master/esignature.rest.swagger-v2.1.json
      Namespace: com.docusign.esign.model
