name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Ddocusign.integrationKey=${{secrets.INTEGRATION_KEY}} -Ddocusign.secretKey=${{secrets.SECRET_KEY}} -Ddocusign.accountId=${{secrets.ACCOUNT_ID}}